test

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,17 +1,13 @@
 #!/bin/bash
+echo "-------------------------------Before assembling"
 
-# restore build artifacts
-if [ "$(ls /tmp/sti/artifacts/ 2>/dev/null)" ]; then
-    mv /tmp/sti/artifacts/* $HOME/.
+/usr/libexec/s2i/assemble
+rc=$?
+
+if [ $rc -eq 0 ]; then
+    echo "---------------------After successful assembling"
+else
+    echo "------------------After failed assembling"
 fi
 
-# move the application source
-mv /tmp/sti/src $HOME/src
-
-# build application artifacts
-pushd ${HOME}
-make all
-
-# install the artifacts
-make install
-popd
+exit $rc
